vich_uploader:
    db_driver: orm
    mappings:
        product_image:
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            uri_prefix: /uploads/images
            delete_on_update: false
            delete_on_remove: false
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer